[package]
name = "rinex_exporter_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.13.1"
rinex = { version = "0.21.1",features = ["full"] }
prometheus = "0.14.0"
anyhow = "1.0.100"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.5.54", features = ["derive", "env"] }
time = "0.3.45"
async-compression = { version = "0.4", features = ["tokio", "gzip"] }